//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaml2DocsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yaml2DocsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   バッチ処理を終了します。(処理時間:{0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBatEndLog {
            get {
                return ResourceManager.GetString("MsgBatEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッチ処理を開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBatStartLog {
            get {
                return ResourceManager.GetString("MsgBatStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理名に誤りがあります。(TargetName:{0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrServiceNotFound {
            get {
                return ResourceManager.GetString("MsgErrServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【{0}】{1}処理が異常終了しました。
        ///{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecFailedLog {
            get {
                return ResourceManager.GetString("MsgExecFailedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【{0}】{1}処理を開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecStartLog {
            get {
                return ResourceManager.GetString("MsgExecStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【{0}】{1}処理が正常に終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecSuccessLog {
            get {
                return ResourceManager.GetString("MsgExecSuccessLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B1001 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SrvIdYml2Md {
            get {
                return ResourceManager.GetString("SrvIdYml2Md", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YAML to Markdown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SrvNmYml2Md {
            get {
                return ResourceManager.GetString("SrvNmYml2Md", resourceCulture);
            }
        }
    }
}
